# Author: Alina Tu
# Contact: alinat2@uci.edu
# Last Updated: 3/12/2022
# About: This preprocessing script is for the Reading Span (Rspan) data files of the Individual Differences 
#        and Robotics (IndivRobotics) project. Reading refers to the sentences used when determining whether 
#        the sentence makes sense. Letter refers to the letters that show up and are recalled in 
#        sequential order.

## This is edited from a duplicate of the Sspan script - still in progress!! ##

# Getting started [PACKAGES AND WORKING DIRECTORY]
install.packages("rprime")
install.packages('dplyr', repos = 'https://cloud.r-project.org')
install.packages("tidyverse")
library(rprime)
library(dplyr)
library(tidyverse)

# Input the working directory containing the Rspan Eprime data files
# Each file is named "RspanShort-" + "subject ID" + "session number" (i.e., RspanShort-111-1.txt)
workdir <- "/Users/alinatu/Downloads/RspanShort/"
setwd(workdir)

# Create a function to organize Eprime data
read <- function(file_name) {
  # Read in a text file generated by Eprime
  file_lines <- read_eprime(file_name)
  # Convert lines from an Eprime file into EprimeFrame objects
  file_frames <- FrameList(file_lines)
  # Make it a data frame
  file_df <- to_data_frame(file_frames)
  # Clean up data
  data <- as_tibble(file_df)
  # data[data == "?"] <- "NA"
}

test_data <- read("RspanShort-789-1.txt")

# Store list of names for all Eprime data files
files <- dir(pattern = "*.txt")

trial_full <- tibble()
recall_full <- tibble()
participant_full <- tibble()

for (indiv_eprime_datafile in files){
  readable_data <- read(indiv_eprime_datafile)
  sub_id <- as.numeric(readable_data$Subject)[1]
  
  # Symmetry-matrix trial sequences
  trial_data <- readable_data[readable_data$Procedure == "trialdo", ]
  trial_proc <- as_tibble(trial_data) %>% # there are 6 test trials
    select(showSentence.RT, SENSEBOTH.ACC, SENSEBOTH.RT)
    # ShowSymm.RT: RT taken to click past the symmetry grid
    # CheckResponse.RT: RT taken to select a true/false response
    # CollectClick.RT: RT taken to select a red square during recall
  trial_proc <- cbind(rep(sub_id, nrow(trial_proc)), trial_proc)
  trial_full <- rbind(trial_full, trial_proc)
  
  # Overall test "recall" trials
  recall_data <- readable_data[readable_data$Procedure == "recall", ]
  recall_proc <- as_tibble(recall_data)[3:8,] %>% # there are 6 test trials
    select(Cycle, Sample, SpanScore, SpanTotal, setsz, numberwrong)
  recall_proc <- cbind(rep(sub_id, nrow(recall_proc)), recall_proc)
  recall_full <- rbind(recall_full, recall_proc)
  
  # Overall scores
  summary_data <- readable_data[readable_data$Procedure == "SessionProc", ]
  summary_proc <- as_tibble(summary_data)[1,] %>%
    select(MathErrorTotal, SpeedErrorTotal, AccErrorTotal, RspanScore, RspanTotal)
    # Rspan Score: sum of SpanScore in each recall_proc procedure (# of correctly recalled letters)
    # note: set size = list length
    # Rspan Total: sum of SpanTotal in each recall_proc procedure (total possible letters to recall)
  avg_showSentence.RT <- mean(as.numeric(trial_proc$showSentence.RT), na.rm = TRUE)
  avg_SENSEBOTH.ACC <- mean(as.numeric(trial_proc$SENSEBOTH.ACC), na.rm = TRUE)
  avg_SENSEBOTH.RT <- mean(as.numeric(trial_proc$SENSEBOTH.RT), na.rm = TRUE)
  summary_proc <- cbind(sub_id, avg_showSentence.RT, avg_SENSEBOTH.ACC, avg_SENSEBOTH.RT, summary_proc)
  participant_full <- rbind(participant_full, summary_proc)
}

colnames(trial_full) <- c("sub_id", "showSentence.RT", "SENSEBOTH.ACC", "SENSEBOTH.RT")
colnames(recall_full) <- c("sub_id", "Cycle", "Sample", "SpanScore", "SpanTotal", "Sets", "numberwrong")

print("Writing CSVs...")
write.csv(trial_full, "Rspan_trial_full.csv")
write.csv(recall_full, "Rspan_recall_full.csv")
write.csv(participant_full, "Rspan_participant_full.csv")

