# Author: Alina Tu
# Contact: alinat2@uci.edu
# Last Updated: 2/26/2022
# About: This preprocessing script is for the Symmetry Span (Sspan) data files of the Individual Differences 
#        and Robotics (IndivRobotics) project. Symmetry refers to the grid used when determining whether 
#        it's symmetrical (SymmetryDisplays: symm number). Matrix refers to the red squares, recalled in 
#        sequential order (MatrixID: matrix number).

# Getting started [PACKAGES AND WORKING DIRECTORY]
install.packages("rprime")
install.packages('dplyr', repos = 'https://cloud.r-project.org')
install.packages("tidyverse")
library(rprime)
library(dplyr)
library(tidyverse)

# Input the working directory containing the Sspan Eprime data files
# Each file is named "SspanShort-" + "subject ID" + "session number" (i.e., SspanShort-111-1.txt)
workdir <- "/Users/alinatu/Downloads/SspanShortdata_pilot_022322/"
setwd(workdir)

# Create a function to organize Eprime data
read <- function(file_name) {
  # Read in a text file generated by Eprime
  file_lines <- read_eprime(file_name)
  # Convert lines from an Eprime file into EprimeFrame objects
  file_frames <- FrameList(file_lines)
  # Make it a data frame
  file_df <- to_data_frame(file_frames)
  # Clean up data
  data <- as_tibble(file_df)
  # data[data == "?"] <- "NA"
}

test_data <- read("SspanShort-805-4.txt")
test_data1 <- read("SspanShort-803-1.txt")
test_data2 <- read("SspanShort-807-1.txt")
test_data3 <- read("SspanShort-810-1.txt")

# Store list of names for all Eprime data files
files <- dir(pattern = "*.txt")

trial_full <- tibble()
recall_full <- tibble()
participant_full <- tibble()

for (indiv_eprime_datafile in files){
  readable_data <- read(indiv_eprime_datafile)
  sub_id <- as.numeric(readable_data$Subject)[1]
  
  # Symmetry-matrix trial sequences
  trial_data <- readable_data[readable_data$Procedure == "trialdo" | readable_data$Procedure == "RedrawProc", ]
  trial_proc <- as_tibble(trial_data) %>% # there are 6 test trials
    select(ShowSymm.RT, CheckResponse.RT, CollectClick.RT)
    # ShowSymm.RT: RT taken to click past the symmetry grid
    # CheckResponse.RT: RT taken to select a true/false response
    # CollectClick.RT: RT taken to select a red square during recall
  trial_proc <- cbind(rep(sub_id, nrow(trial_proc)), trial_proc)
  trial_full <- rbind(trial_full, trial_proc)
  
  # Overall test "recall" trials
  recall_data <- readable_data[readable_data$Procedure == "recall", ]
  recall_proc <- as_tibble(recall_data)[3:8,] %>% # there are 6 test trials
    select(Cycle, Sample, SpanScore, SpanTotal)
  recall_proc <- cbind(rep(sub_id, nrow(recall_proc)), recall_proc)
  recall_full <- rbind(recall_full, recall_proc)
  
  # Overall scores
  summary_data <- readable_data[readable_data$Procedure == "SessionProc", ]
  summary_proc <- as_tibble(summary_data)[1,] %>%
    select(SymmErrorTotal, SpeedErrorTotal, AccErrorTotal, SspanScore, SspanTotal)
    # Sspan Score: sum of SpanScore in each recall_proc procedure (# of correctly recalled red squares)
    # note: set size = list length
    # Sspan Total: sum of SpanTotal in each recall_proc procedure (total possible red squares to recall)
  avg_ShowSymm.RT <- mean(as.numeric(trial_proc$ShowSymm.RT), na.rm = TRUE)
  avg_CheckResponse.RT <- mean(as.numeric(trial_proc$CheckResponse.RT), na.rm = TRUE)
  avg_CollectClick.RT <- mean(as.numeric(trial_proc$CollectClick.RT), na.rm = TRUE)
  summary_proc <- cbind(sub_id, avg_ShowSymm.RT, avg_CheckResponse.RT, avg_CollectClick.RT, summary_proc)
  participant_full <- rbind(participant_full, summary_proc)

  # 1. (later) pull RTs per trial thing
}

colnames(trial_full) <- c("sub_id", "ShowSymm.RT", "CheckResponse.RT", "CollectClick.RT")
colnames(recall_full) <- c("sub_id", "Cycle", "Sample", "SpanScore", "SpanTotal")

print("Writing CSVs...")
write.csv(trial_full, "Sspan_trial_full.csv")
write.csv(recall_full, "Sspan_recall_full.csv")
write.csv(participant_full, "Sspan_participant_full.csv")

# cycle, sample, wordselection (combination of array#), symmetry time?
# Symm.ACC and Symm.RT refer to practice trials for true/false symmetry grid

# test_datas <- map_df(files, organize)
# test_datas$SspanScore