install.packages("rprime")
install.packages("dpylr")
install.packages("tidyverse")
library(rprime)
library(dplyr)
library(tidyverse)

sspan_data <- read_eprime("/Users/alinatu/Downloads/SspanShortdata_pilot_022322/SspanShort-803-1.txt")

setwd("/Users/alinatu/Downloads/SspanShortdata_pilot_022322/")

# A function to prepare all eprime data simultaneously
reduce <- function(path) {
  # Read in a text file generated by Eprime
  lines <- read_eprime(path)
  # Convert lines from an Eprime file into EprimeFrame objects
  frames <- FrameList(lines)
  # Make it a data frame.
  experiment_df <- to_data_frame(frames)
  # Select the columns we want for a tibble called "dat".
  dat <- as_tibble(experiment_df) %>%
    select(
      Subject, Procedure, correctResp, Symm.RT, 
      ShowSymm.RT, CheckResponse.RT, SpanScore, SpanTotal, numberwrong,
      SymmErrorTotal, AccErrorTotal, SspanScore, SspanTotal
    )
  dat[dat == "?"] <- "NA"
  # Only put the actual trials in "dat".
  dat <- dat
}

test_dat <- reduce("SspanShort-805-4.txt")
test_dat1 <- reduce("SspanShort-803-1.txt")
test_dat2 <- reduce("SspanShort-807-1.txt")
test_dat3 <- reduce("SspanShort-810-1.txt")


nrow(test_dat)
files <- dir(pattern = "*.txt")
files
test_dats <- map_df(files, reduce)
test_dats$SspanScore